### ISSUE TITLE
Unable to find package 'KoreBuild'

### ISSUE THREAD

**Issue by asbjornu** [aspnet/Signing#11]
Executing `build.sh` yields the following error:

> Unable to find package 'KoreBuild'.

When searching for [KoreBuild on NuGet](https://www.nuget.org/packages?q=KoreBuild), there is indeed no package by that name. There is a [repository on GitHub called KoreBuild](https://github.com/aspnet/KoreBuild), but that doesn't really help `nuget install`. What's the expected environment for `build.sh` supposed to look like for it to execute successfully?

**Comment by analogrelay** [comment]
Unfortunately this repo is quite out of date and our build system has advanced quite far since we stopped building this repo. We're no longer working on package signing in this repository, any package signing work will happen over in the NuGet Team (see their repo: http://github.com/NuGet/Home). I don't know what their timeline or plans are for signing but I know it's on their radar.

I'll update the README to clarify the situation.

**Comment by asbjornu** [comment]
@anurse: Thanks.
